#!/usr/bin/env sh
# Gradle wrapper script (UNIX)
# Generated by assistant - do not modify unless you know what you're doing.

#############################################################################
# Start of standard gradlew wrapper script
#############################################################################

prog="$0"
exec 0<&- || true

# OS-specific support.  $var _must_ be set to either true or false.
cygwin=false
msys=false
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  MINGW*|MSYS*) msys=true ;;
esac

# For Cygwin, ensure paths are in UNIX format before we start
if $cygwin ; then
  [ -n "$JAVA_HOME" ] && JAVA_HOME="`cygpath --unix "$JAVA_HOME"`"
fi

# Determine JAVA_HOME if not set
if [ -z "$JAVA_HOME" ]; then
  if [ -n "$(command -v java 2>/dev/null)" ]; then
    # try to find java home from java command
    _java_cmd="$(command -v java)"
    _java_bin_dir="$(dirname "$_java_cmd")"
    JAVA_HOME="$(cd "$_java_bin_dir/.." && pwd -P)"
  fi
fi

CLASSPATH=""
APP_NAME="Gradle Wrapper"

# Default wrapper jar location
WRAPPER_JAR="gradle/wrapper/gradle-wrapper.jar"
WRAPPER_BASEDIR="$(dirname "$prog")"

if [ ! -f "$WRAPPER_BASEDIR/$WRAPPER_JAR" ]; then
  echo "WARNING: Wrapper jar not found at $WRAPPER_BASEDIR/$WRAPPER_JAR"
  echo "You need to generate or add gradle-wrapper.jar to the repository."
  echo "Run 'gradle wrapper' locally to create it, then commit the jar to this branch."
fi

JAVA_EXE="${JAVA_HOME:+$JAVA_HOME/bin/}java"

# Exec Java with the wrapper jar
exec "$JAVA_EXE" -classpath "$WRAPPER_BASEDIR/$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"

#############################################################################
# End of standard gradlew wrapper script
#############################################################################
