@echo off
rem Gradle wrapper batch file (Windows)
rem Generated by assistant - do not modify unless you know what you're doing.

@SETLOCAL
nrem Resolve links - get the absolute path to this script
set PRG=%~dp0%~nx0
set SCRIPT_DIR=%~dp0
nrem Set default JAVA_HOME if not set (optional)nrem if not defined JAVA_HOME (
rem   set JAVA_HOME=C:\Program Files\Java\jdk-21
rem )
nset WRAPPER_JAR=%SCRIPT_DIR%gradle\wrapper\gradle-wrapper.jarnnif not exist "%WRAPPER_JAR%" (
  echo WARNING: gradle-wrapper.jar not found at %WRAPPER_JAR%
  echo You need to generate or add gradle-wrapper.jar to the repository.
  echo Run "gradle wrapper" locally to create it, then commit the jar to this branch.
)
n"%JAVA_HOME%\bin\java" -classpath "%WRAPPER_JAR%" org.gradle.wrapper.GradleWrapperMain %*
